export type AboutChunk = {
  id: string;
  title: string;
  content: string;
  keywords: string[];
  priority: number;
  pinned?: boolean;
};

export const aboutChunks: AboutChunk[] = [
  {
    id: 'profile',
    title: 'Profile',
    pinned: true,
    priority: 100,
    keywords: ['hoa trinh hai', 'hoa', 'kyle', 'profile', 'about', 'bio', 'role', 'location'],
    content: [
      'Name: Hoa Trinh Hai (Hoa, Kyle)',
      'Role: Senior Software Engineer',
      'Location: Vietnam',
      'Email: hi@hoatrinh.dev',
      'Summary: I am a senior software engineer with 13+ years building web products across frontend, full-stack, and AI-assisted systems.',
    ].join('\n'),
  },
  {
    id: 'current-work',
    title: 'Current work',
    priority: 95,
    keywords: ['current work', 'oneqode', 'frontier', 'product lead', 'current role'],
    content: [
      'Company: OneQode',
      'Role: Senior Software Engineer (Contract, Product Lead)',
      'Dates: 2025-10 to present',
      'Summary: Product Lead for Frontier, covering architecture, delivery systems, and product execution from early prototype to commercial rollout.',
      'Highlights:',
      '- Lead Frontier from AI-scaffolded prototype to commercial platform, owning architecture, delivery flow, and product direction.',
      '- Shipped an interactive 3D globe and AI-guided data center explorer used in investor and partner demos.',
      '- Delivered the commercial core: quoting, dynamic pricing, partner white-labeling, plus the monorepo and Nuxt 4 migration behind it.',
      '- Own the roadmap for Identity and WHMCS billing integrations that support onboarding and global expansion.',
    ].join('\n'),
  },
  {
    id: 'experience-overview',
    title: 'Experience overview',
    priority: 90,
    keywords: ['experience', 'career', 'resume', 'cv', 'work history'],
    content: [
      'Roles:',
      '- OneQode: Senior Software Engineer (Contract, Product Lead), 2025-10 to present.',
      '- InferenceCloud.ai: Senior Frontend Developer (Contract), 2023-05 to 2025-09.',
      '- Storyroom: Senior Frontend Developer (Contract), 2021-09 to 2023-04.',
      '- Upwork: Full Stack Engineer (Freelance), 2020-04 to 2025-04.',
      '- DesignBold: Senior Lead Software Engineer, 2019-09 to 2021-09.',
      '- DesignBold: Full Stack Developer, 2016-01 to 2019-09.',
      '- Netlink Solutions: Backend Developer, 2012-04 to 2016-01.',
    ].join('\n'),
  },
  {
    id: 'experience-inferencecloud',
    title: 'InferenceCloud.ai',
    priority: 98,
    keywords: [
      'inferencecloud',
      'inference cloud',
      'inferencecloud ai',
      'notebook',
      'machine learning',
      'data science',
      'ml',
      'vue',
      'nuxt',
      'tailwind',
      'd3',
      'cypress',
      'aws amplify',
    ],
    content: [
      'Company: InferenceCloud.ai',
      'Role: Senior Frontend Developer (Contract)',
      'Dates: 2023-05 to 2025-09',
      'Location: Remote',
      'Tech: TypeScript, Vue.js, Nuxt.js, Tailwind CSS, D3.js, Cypress',
      'Highlights:',
      '- Led frontend delivery across six AI-driven products spanning business analysis, media insights, and content planning.',
      '- Built a reusable component system that cut UI implementation time by about 30%.',
      '- Introduced AI-assisted development workflows that doubled team delivery over six months.',
      '- Rebuilt AWS Amplify CI/CD and added Cypress coverage, reducing bug-resolution time by 30%.',
      '- Facilitated planning and retrospectives that improved team efficiency by 20% within six months.',
      'Additional context:',
      '- Worked on a cloud notebook product for data science and machine learning with real-time code execution, data visualization, collaboration, version-control flows, and export features.',
      '- The main documented frontend stack centered on Vue 3, TypeScript, Vite, Pinia, Tailwind CSS, Vue Router, D3.js, Cypress, and AWS Amplify.',
      '- The README positioned the product around helping teams experiment, analyze, and share insights in AI-heavy workflows.',
    ].join('\n'),
  },
  {
    id: 'experience-storyroom',
    title: 'Storyroom',
    priority: 94,
    keywords: [
      'storyroom',
      'brand analysis',
      'data provider',
      'data writer',
      'profile management',
      'nuxt',
      'vue',
      'd3',
      'express',
      'node',
    ],
    content: [
      'Company: Storyroom',
      'Role: Senior Frontend Developer (Contract)',
      'Dates: 2021-09 to 2023-04',
      'Location: Remote',
      'Tech: Vue.js, Nuxt.js, TypeScript, Node.js, Tailwind CSS, D3.js',
      'Highlights:',
      '- Led the migration from Vue and Nuxt 2 to Vue and Nuxt 3, cutting page-load times roughly in half.',
      '- Diagnosed and removed D3 bottlenecks in data-heavy views, lifting user satisfaction by about 30% in three months.',
      '- Built interactive Vue and D3 visualizations that increased product engagement 30% over six months.',
      'Additional context:',
      '- Storyroom combined a Nuxt-based user app and admin dashboard with multiple Node and Express backend services for profile management, data provider orchestration, data writing, and brand analysis.',
      '- Data-provider acted as the orchestrator for SSOT keyword and relationship data, with writer-service triggers when source data was missing.',
      '- Brand-analysis focused on generating topic strategies and related metrics, while DevOps tools handled workspace bootstrapping plus keyword-class and voice-of-customer setup.',
    ].join('\n'),
  },
  {
    id: 'experience-upwork',
    title: 'Upwork',
    priority: 92,
    keywords: [
      'upwork',
      'freelance',
      'clients',
      'shopify',
      'recruitmate',
      'twise',
      'webflow',
      'openai',
      'mailerlite',
      'simple texting',
      'mealie',
      'wordpress',
      'strapi',
      'nest',
    ],
    content: [
      'Company: Upwork',
      'Role: Full Stack Engineer (Freelance)',
      'Dates: 2020-04 to 2025-04',
      'Location: Remote',
      'Tech: Vue.js, React.js, D3.js, Node.js, WordPress, Shopify',
      'Highlights:',
      '- Delivered product, marketing, and data-visualization work for 30+ clients while maintaining 100% Job Success and Top Rated Plus status.',
      '- Built high-performance landing pages, interactive charts, and motion-heavy UI that lifted engagement by roughly 20%.',
      '- Improved WordPress and Shopify Core Web Vitals, cutting load times by as much as 60%.',
      '- Turned short projects into long-term client relationships, growing repeat business by about 30%.',
      'Additional context:',
      '- README discovery across other client folders showed work spanning recruitment SaaS, Shopify storefronts, CMS and API integrations, food and recipe products, Webflow apps, and AI-oriented web experiences.',
      '- Representative projects included RecruitMate, a Nuxt plus Supabase recruitment platform; Twise web and canvas apps built with Next.js and Nuxt; a Webflow hybrid app that used OpenAI image generation; and a MailerLite plus SimpleTexting subscription API.',
      '- The surrounding repos also pointed to hands-on delivery across Shopify Dawn-based themes, Vue and Nuxt frontends, React apps, Nest and Strapi services, and self-hosted product customization work such as recipe and meal-planning software.',
    ].join('\n'),
  },
  {
    id: 'projects',
    title: 'Projects',
    priority: 85,
    keywords: [
      'projects',
      'project',
      'keepgoing',
      'pacelingo',
      'win95 fun',
      'win95',
      'side projects',
    ],
    content: [
      'Featured projects:',
      '- KeepGoing (2026): developer momentum toolkit for resuming side projects with context, checkpoints, and AI-aware handoffs.',
      '- PaceLingo (2026): private AI English coach for family learning with voice-first practice and personalized feedback.',
      '- Win95.fun (2025): browser arcade with Windows 95-inspired UX, leaderboards, monthly challenges, and unlockable themes.',
    ].join('\n'),
  },
  {
    id: 'skills',
    title: 'Skills',
    priority: 80,
    keywords: [
      'skills',
      'skill',
      'tech',
      'stack',
      'tools',
      'languages',
      'frontend',
      'backend',
      'platform',
      'ai tooling',
    ],
    content: [
      'Focus: Product-minded engineering, system design, agentic workflows, technical leadership, AI-assisted delivery.',
      'Languages: TypeScript, JavaScript, Kotlin, Dart, Python, PHP.',
      'Frontend: SolidJS, Vue / Nuxt, Svelte / SvelteKit, Astro, React, Flutter, Tailwind CSS, D3.js.',
      'Backend: Bun, Node.js, Firebase, Cloud Functions, Laravel, REST APIs.',
      'Platform: Cloudflare Pages / D1 / Workers, AWS Amplify, Docker, Turborepo, monorepos, CI/CD.',
      'AI tooling: Claude Code, MCP, Cursor, Gemini, OpenAI.',
    ].join('\n'),
  },
  {
    id: 'links',
    title: 'Links',
    priority: 70,
    keywords: ['contact', 'email', 'github', 'linkedin', 'links', 'reach', 'contact info'],
    content: [
      'Email: hi@hoatrinh.dev',
      'GitHub: https://github.com/mrth2',
      'LinkedIn: https://www.linkedin.com/in/hoa-trinh-dev/',
    ].join('\n'),
  },
];
