export const aboutPromptContext = [
  'Profile:',
  '- Name: Hoa Trinh Hai (Hoa, Kyle)',
  '- Role: Senior Software Engineer',
  '- Location: Vietnam',
  '- Email: hi@hoatrinh.dev',
  '- Current focus: product-minded engineering, system design, agentic workflows, AI-assisted delivery',
  '',
  'Current work:',
  '- Product Lead for Frontier at OneQode (architecture, delivery systems, product execution).',
  '',
  'Projects:',
  '- KeepGoing (2026): developer momentum toolkit for resuming side projects.',
  '- PaceLingo (2026): private AI English coach for family learning.',
  '- Win95.fun (2025): browser arcade with Windows 95-inspired UX.',
  '',
  'Experience (selected):',
  '- OneQode: Senior Software Engineer (Contract, Product Lead), 2025-10 to present.',
  '- InferenceCloud.ai: Senior Frontend Developer (Contract), 2023-05 to 2025-09.',
  '- Storyroom: Senior Frontend Developer (Contract), 2021-09 to 2023-04.',
  '- Upwork: Full Stack Engineer (Freelance), 2020-04 to 2025-04.',
  '- DesignBold: Senior Lead Software Engineer, 2019-09 to 2021-09.',
  '- DesignBold: Full Stack Developer, 2016-01 to 2019-09.',
  '- Netlink Solutions: Backend Developer, 2012-04 to 2016-01.',
  '',
  'Skills:',
  '- TypeScript, JavaScript, Kotlin, Python, PHP',
  '- SolidJS, Vue/Nuxt, Svelte/SvelteKit, Astro, React, Flutter',
  '- Bun, Node.js, Firebase, Laravel, REST APIs',
  '- Cloudflare Pages/Workers/D1, Docker, monorepos, CI/CD',
  '',
  'Links:',
  '- GitHub: https://github.com/mrth2',
  '- LinkedIn: https://www.linkedin.com/in/hoa-trinh-dev/',
].join('\n');

export const aboutKeywords = [
  'hoa',
  'trinh',
  'hai',
  'kyle',
  'hoatrinh',
  'portfolio',
  'profile',
  'about',
  'role',
  'location',
  'email',
  'contact',
  'github',
  'linkedin',
  'project',
  'projects',
  'keepgoing',
  'pacelingo',
  'win95',
  'win95fun',
  'experience',
  'career',
  'resume',
  'cv',
  'skills',
  'tech',
  'stack',
  'oneqode',
  'frontier',
  'inferencecloud',
  'storyroom',
  'upwork',
  'designbold',
  'netlink',
];
